name: Lean + Coq CI

on: [push, pull_request]

jobs:
  coq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Coq 9.0.0 using docker-coq-action
        uses: coq-community/docker-coq-action@v1
        with:
          opam_file: none
          image: 'coqorg/coq:9.0.0'
          custom_script: |
            coqc --version
            coqc proofs/lean_coq/check_and_conclude_exact_from_user.v

  lean:
    runs-on: ubuntu-latest
    continue-on-error: true
    container: ghcr.io/leanprover-community/lean:3.52.0
    steps:
      - uses: actions/checkout@v4
      - name: Run Lean check (non-blocking)
        run: |
          lean --version || true
          if [ -f proofs/lean_coq/check_and_conclude_exact_from_user.lean ]; then
            lean -j1 proofs/lean_coq/check_and_conclude_exact_from_user.lean || true
          elif [ -f code/repo_from_zip/check_and_conclude_exact_from_user.lean ]; then
            lean -j1 code/repo_from_zip/check_and_conclude_exact_from_user.lean || true
          else
            echo "Lean file not found";
          fi
