name: Lean + Coq CI (numeric checks, docker-based)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lean:
    name: Lean numeric check (Docker)
    runs-on: ubuntu-latest
    container:
      image: leanprover/lean:3.52.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show lean version
        run: |
          lean --version || true

      - name: Run Lean numeric check (in container)
        run: |
          # adjust path if your file is in a subfolder; this uses repo root
          if [ -f "./check_and_conclude_exact_from_user.lean" ]; then
            lean --run check_and_conclude_exact_from_user.lean
          elif [ -f "./proofs/check_and_conclude_exact_from_user.lean" ]; then
            lean --run proofs/check_and_conclude_exact_from_user.lean
          else
            echo "ERROR: Lean script not found in repo root or proofs/ - expected check_and_conclude_exact_from_user.lean"
            echo "Files in repo root:"
            ls -la
            exit 2
          fi

  coq:
    name: Coq numeric check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Coq
        run: |
          sudo apt-get update
          sudo apt-get install -y coq

      - name: Run Coq numeric check from proofs/
        run: |
          # The Coq file is expected under proofs/
          if [ -f "./check_and_conclude_exact_from_user.v" ]; then
            coqc check_and_conclude_exact_from_user.v
          elif [ -f "./proofs/check_and_conclude_exact_from_user.v" ]; then
            coqc proofs/check_and_conclude_exact_from_user.v
          else
            echo "ERROR: Coq file check_and_conclude_exact_from_user.v not found in repo root or proofs/."
            echo "Files in repo root:"
            ls -la
            echo "Files in proofs/:"
            ls -la proofs || true
            exit 2
          fi
