name: Lean + Coq CI

on: [push, pull_request]

jobs:
  coq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Coq from apt
        run: |
          sudo apt-get update -y
          sudo apt-get install -y coq
          coqc --version
      - name: Run Coq check
        run: |
          coqc proofs/lean_coq/check_and_conclude_exact_from_user.v
