name: Lean + Coq CI (installer based)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install prerequisites
        run: sudo apt-get update && sudo apt-get install -y curl unzip build-essential

      - name: Install elan (non-interactive)
        run: |
          curl -sL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | bash -s -- -y --default-toolchain leanprover-community/lean:3.52.0
          echo 'export PATH="$HOME/.elan/bin:$PATH"' >> $GITHUB_ENV
          echo 'source $HOME/.elan/env' >> $GITHUB_ENV

      - name: Show lean version and run check
  run: |
    # load elan environment in this shell (do not write `source` into $GITHUB_ENV)
    source $HOME/.elan/env || true
    elan --version || true
    lean --version || true

    # try plausible locations for the Lean script
    if [ -f "./check_and_conclude_exact_from_user.lean" ]; then
      source $HOME/.elan/env && lean --run check_and_conclude_exact_from_user.lean
    elif [ -f "./proofs/lean_coq/check_and_conclude_exact_from_user.lean" ]; then
      source $HOME/.elan/env && lean --run proofs/lean_coq/check_and_conclude_exact_from_user.lean
    else
      echo "ERROR: Lean script not found. Searched ./ and ./proofs/lean_coq/."
      ls -la
      ls -la proofs || true
      exit 2
    fi
