name: Lean + Coq CI (robust, elan action)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lean:
    name: Lean numeric check (elan action)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup elan & Lean toolchain
        uses: leanprover/elan-action@v1
        with:
          toolchain: leanprover-community/lean:3.52.0
          accept-licenses: true

      - name: Verify Lean and run check
        run: |
          source $HOME/.elan/env || true
          lean --version || true
          if [ -f "./check_and_conclude_exact_from_user.lean" ]; then
            lean --run check_and_conclude_exact_from_user.lean
          elif [ -f "./proofs/lean_coq/check_and_conclude_exact_from_user.lean" ]; then
            lean --run proofs/lean_coq/check_and_conclude_exact_from_user.lean
          else
            echo "ERROR: Lean script not found. Searched ./ and ./proofs/lean_coq/."
            ls -la
            ls -la proofs || true
            exit 2
          fi

  coq:
    name: Coq numeric check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Coq
        run: |
          sudo apt-get update
          sudo apt-get install -y coq

      - name: Run Coq numeric check (from proofs/lean_coq)
        run: |
          if [ -f "./check_and_conclude_exact_from_user.v" ]; then
            coqc check_and_conclude_exact_from_user.v
          elif [ -f "./proofs/lean_coq/check_and_conclude_exact_from_user.v" ]; then
            coqc proofs/lean_coq/check_and_conclude_exact_from_user.v
          else
            echo "ERROR: Coq file not found in root or proofs/lean_coq/."
            ls -la
            ls -la proofs || true
            exit 2
          fi
